blog_system/blog/urls.py
from django.conf.urls import patterns, url, include
from blog.feeds import EntradasFeed
from blog.views import LoginView
from django.conf import settings

urlpatterns = patterns('',
                       url(r'^$', settings.BLOG_ENTRIES_HOME_VIEW, name='home'),
                       url(r'^post/detail/(?P<slug>.*)/$', settings.BLOG_ENTRIES_ENTRY_DETAIL_VIEW, name='post'),
                       url(r'^feeds/$', EntradasFeed()),
                       url(r'^ckeditor/', include('ckeditor.urls')),
                       url(r'^post/add/$', settings.BLOG_ENTRIES_ENTRY_CREATE_VIEW, name='new_post'),
                       url(r'^entries/$', settings.BLOG_ENTRIES_ENTRIES_ADMIN_VIEW, name='edit_entries'),
                       url(r'^categories/$', settings.BLOG_ENTRIES_CATEGORIES_ADMIN_VIEW, name='categories'),
                       url(r'^category/add/$', settings.BLOG_ENTRIES_CREATE_CATEGORY_VIEW, name='create_category'),
                     #  url(r'^month/(?P<year>\d+)/(?P<month>\w+)/$', settings.BLOG_ENTRIES_MONTH_VIEW, name='month'),
                       url(r'^post/edit/(?P<slug>.*)/$', settings.BLOG_ENTRIES_ENTRY_UPDATE_VIEW, name='edit'))

blog_system/blog_system/urls.py
# from __future__ import
from django.conf.urls import patterns, include, url
from blog_system import settings
from blog.feeds import EntradasFeed
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from blog.views import LoginView


# admin.autodiscover()

urlpatterns = patterns('',
                       url(r'login/$', LoginView.as_view(), name='login'),
                       url(r'logout/$', 'blog.views.log_out', name='logout'),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'blog/',include('blog.urls') , name='login'))

blog_system/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import os
from datetime import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.utils.text import slugify

STATUS_CHOICES = (
    ('D', 'Draft'),
    ('U', 'Published'),
    ('H', 'Hidden'),
)


class Category(models.Model):
    name = models.CharField(max_length=30, primary_key=True, unique=True)
    description = models.TextField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name.encode('utf-8')


class Tags(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name.encode('utf-8')


class BlogEntry(models.Model):
    def url(self, filename):
        filename, ext = os.path.splitext(filename.lower())
        filename = "%s->%s%s" % (slugify(filename), datetime.now().strftime('%Y-%m-%d.%H-%M-%S'), ext)
        return 'photos/%s' % filename

    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    abstract = models.TextField()
    content = models.TextField()
    image = models.ImageField(upload_to=url)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    category = models.ForeignKey(Category)
    comment = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tags)
    tags.help_text = None
#        return reverse('blog', args={'slug': self.slug})

    def get_absolute_url(self):
        # return reverse('post', self.slug)
        return '/blog/%s' % self.slug

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


@receiver(signals.pre_save, sender=BlogEntry)
def pre_save_format_tags(sender, **kwargs):
    if not kwargs['instance'].slug:
        kwargs['instance'].slug = slugify(kwargs['instance'].title)


class comentarios(models.Model):
    Blog = models.ForeignKey(BlogEntry)
    nombre = models.CharField(max_length=200, blank=True, null=True)
    cuerpo = models.TextField(verbose_name="Comentario", max_length=120)
    fecha_pub = models.DateTimeField(auto_now_add=True, editable=False)

blog_system/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.core.urlresolvers import reverse, reverse_lazy
from .models import BlogEntry, comentarios, Tags, Category, STATUS_CHOICES
from .forms import ComentarioForm, UpdateBlogEntryForm, LoginForm, BlogEntryForm, CategoryForm, filter_form, DeleteCategory
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from endless_pagination.views import AjaxListView
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
import json


MONTHS_DIC = {
    _('January'): 1, _('February'): 2, _('March'): 3, _('April'): 4, _('May'): 5, _('June'): 6,
    _('July'): 7, _('Agoust'): 8, _('September'): 9, _('October'): 10, _('November'): 11, _('December'): 12
}


class Home(AjaxListView):
    model = BlogEntry
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/index.html'
    page_template = 'blog/blog_entries.html'

    def get_context_data(self, **kwargs):
        ctx = super(Home, self).get_context_data(**kwargs)
        ctx['paginate_by'] = self.paginate_by
        if self.request.GET.get('category'):
            ctx['category'] = self.request.GET.get('category')
        if self.request.GET.get('year') and self.request.GET.get('month'):
            ctx['endlesspagination'] = True
        return ctx

    def get_queryset(self):
        c = self.request.GET.get('category')
        y = self.request.GET.get('year')
        m = self.request.GET.get('month')
        if c:
            return BlogEntry.objects.filter(category__name=c).filter(status='U').order_by('-created_at')
        elif y and m:
            return BlogEntry.objects.filter(created_at__year=int(y), created_at__month=MONTHS_DIC[m])
        return BlogEntry.objects.filter(status='U').order_by('-created_at')


class AdminEntries(ListView):
    model = BlogEntry
    context_object_name = 'posts'
    template_name = 'blog/admin_entries.html'

    def get_context_data(self, **kwargs):
        ctx = super(AdminEntries, self).get_context_data(**kwargs)
        request_get = self.request.GET.copy()
        if 'page' in request_get:
            del request_get['page']
        ctx['get_query'] = request_get
        ctx['status'] = STATUS_CHOICES
        if self.request.GET.get('search') or self.request.GET.get('category') or self.request.GET.get('status'):
            ctx['form'] = filter_form({'search': self.request.GET.get('search'),
                                       'category': self.request.GET.get('category'),
                                       'status': self.request.GET.get('status')})
        else:
            ctx['form'] = filter_form()
        return ctx

    def post(self, request):
        form = UpdateBlogEntryForm(request.POST)
        if self.request.is_ajax() and form.is_valid():
            # post = form.save(commit=False)
            postid = form.cleaned_data['post_id']
            newcate = form.cleaned_data['category']
            newstatus = form.cleaned_data['status']
            comment = form.cleaned_data['comment'] == 'true'
            post = get_object_or_404(BlogEntry, pk=postid)
            post.comment = comment
            post.category = get_object_or_404(Category, name=newcate)
            post.status = newstatus
            post.save()
            return HttpResponse(json.dumps({'Success': 'Success'}), content_type='application/json')

    def get_queryset(self):
        filter_search = self.request.GET.get('search')
        filter_category = self.request.GET.get('category')
        filter_status = self.request.GET.get('status')
        if filter_search:
            queryset = BlogEntry.objects.filter(Q(title__icontains=filter_search) |
                                                     Q(tags__name__icontains=filter_search)).distinct().order_by('-created_at')
        else:
            queryset = BlogEntry.objects.all().order_by('-created_at')
        if filter_category:
            queryset = queryset.filter(category=filter_category)
        if filter_status:
            queryset = queryset.filter(status=filter_status)
        return queryset


class BaseBlogEntry(FormView):
    form_class = BlogEntryForm
    template_name = 'blog/edit_entry.html'

    def get_context_data(self, **kwargs):
        context = super(BaseBlogEntry, self).get_context_data(**kwargs)
        context['category_form'] = CategoryForm()
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        tags = unicode(form.cleaned_data['tags']).split(',')
        lst_tgs = []
        for tag in tags:
            lst_tgs.append(Tags.objects.get_or_create(name=tag)[0])
        post.tags = lst_tgs
        post.save()
        return HttpResponseRedirect(reverse('home'))


class CreateBlogEntry(BaseBlogEntry, CreateView):
    initial = {'status': 'D'}


class UpdateBlogEntry(BaseBlogEntry, UpdateView):
    context_object_name = 'post'

    def get_object(self, queryset=None):
        post = get_object_or_404(BlogEntry, slug=self.kwargs['slug'])
        return post


class AdminCategories(ListView):
    model = Category
    context_object_name = 'model'
    template_name = 'blog/categories.html'

    def get_context_data(self, **kwargs):
        ctx = super(AdminCategories, self).get_context_data(**kwargs)
        ctx['form'] = CategoryForm()
        ctx['js_functions'] = 'category_template()'
        return ctx

    def get_queryset(self):
        qs = super(AdminCategories, self).get_queryset()
        return qs.exclude(name="Default")

    def post(self, request, *args, **kwargs):
        form = DeleteCategory(request.POST)
        if self.request.is_ajax() and form.is_valid():
            category = get_object_or_404(Category, name=form.cleaned_data['category_name'])
            category.delete()
            return HttpResponse(json.dumps({'Success': 'Success'}), content_type='application/json')


class CreateCategory(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.is_ajax():
            return HttpResponseRedirect(reverse('home'))
        return super(CreateCategory, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = CategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            cate, created = Category.objects.get_or_create(name=name, description=description)
            return HttpResponse(json.dumps({'name': cate.name, 'created': created}), content_type='application/json')
        return HttpResponse(json.dumps({'created': False}), content_type='application/json')


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.cleaned_data['username']
        passw = form.cleaned_data['password']

        user = authenticate(username=user, password=passw)

        if user is not None and user.is_active:
            login(self.request, user)
        return super(LoginView, self).form_valid(form)


class BlogEntryDetail(DetailView):
    model = BlogEntry
    template_name = 'blog/article.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        ctx = super(BlogEntryDetail, self).get_context_data(**kwargs)
        ctx['comentarios'] = comentarios.objects.filter(Blog__slug=self.kwargs['slug']).order_by('-fecha_pub')
        ctx['comentariosForm'] = ComentarioForm()
        return ctx

    def post(self, request, *args, **kwargs):
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.Blog = get_object_or_404(BlogEntry, slug=self.kwargs['slug'])
            comentario.save()
            return HttpResponseRedirect(reverse('post', kwargs={'slug': self.kwargs['slug']}))


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


home = Home.as_view()
admin_entries = login_required(AdminEntries.as_view())
blog_entry_detail = BlogEntryDetail.as_view()
create_blog_entry = login_required(CreateBlogEntry.as_view())
update_blog_entry = login_required(UpdateBlogEntry.as_view())
create_category = login_required(CreateCategory.as_view())
admin_categories = login_required(AdminCategories.as_view())

blog_system/templates/blog/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="#">

        <title>Blog Template for Bootstrap</title>

        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Template -->
        <script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/addpost.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
        <!-- Style -->
        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/facebook.png' %}">


        <!-- Custom styles for this template -->
        <link href="{% static 'css/blog.css'%}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

    </head>

    <body>

<body>
<!-- Header -->
<div class="blog-masthead hidden-print">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="{% url 'home' %}">Home</a>
            <a class="blog-nav-item" href="#">New features</a>
            <a class="blog-nav-item" href="#">Press</a>
            <a class="blog-nav-item" href="#">New hires</a>
            <a class="blog-nav-item" href="#">About</a>
            <!--<form class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control input-sm" name="search" id="search-nav-input" placeholder="Buscar">
                    <span class="input-group-btn">
                    <button type="submit" class="btn btn-sm" title="Buscar"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </form>-->
        </nav>
    </div>
</div>

    {% if user.is_superuser %}
    <div class="admin-tools hidden-print">
        <i class="fa fa-cog"></i>
        <ul class="admin-items">
            <li><a href="{% url 'new_post' %}">Nuevo Post</a></li>
            <li><a href="{% url 'edit_entries' %}">Publicaciones</a></li>
            <li><a href="{% url 'categories' %}">Categorias</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
    {% endif %}
<!-- End Headder -->
    {% block content %}

    {% endblock %}
<!-- Footer -->
    <footer class="blog-footer">
        <p>Blog template by <a href="https://www.deipi.com">Deipi.com</a>.</p>
        <p>
            <a href="#" class="hidden-print">Back to top</a>
        </p>
    </footer>
</body>
</html>

blog_system/templates/blog/admin_entries.html
{% extends 'blog/admin.html' %}
<!-- Container -->
{% block content %}
<div class="container">
    {% if user.is_superuser %}
        <div class="text-center">
            <h1>Publicaciones</h1>
        </div>
        <div class="row">
        {% csrf_token %}
                {% load crispy_forms_tags %}
                    {% crispy form %}
                <table class="table table-striped">
                    <tr>
                        <th class="col-md-1">Imagen</th>
                        <th class="col-md-6">Información</th>
                        <th class="col-md-1">Coment</th>
                        <th class="col-md-2">Categoria</th>
                        <th class="col-md-1">Estado</th>
                        <th class="col-md-1">Guardar</th>
                    </tr>
                    {% if not posts %}
                    <tr><th>No Entries<th></tr>
                    {% endif %}
                    {% for post in posts %}
                    <tr class="infopost" id="post_{{ post.pk }}">
                        <td>
                            <img src="{{ post.image.url }}" class='post-image'>
                        </td>
                        <td>
                            <div class="title">
                                <a href="{% url 'edit' post.slug %}">{{ post.title|truncatechars:60 }}</a>
                            </div>
                            {% autoescape off %}
                                <div class="abstract">{{ post.abstract|truncatechars:150 }}</div>
                            {% endautoescape %}
                           <ul class="tags_list">
                            {% for tag in post.tags.all %}
                                <li class="isTag">{{ tag }}</li>
                            {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <center>
                                {% if post.comment == True %}
                                <input class="comentar" id="id_comment" name="comentar" type="checkbox" checked>
                                {% else %}
                                <input class="comentar" id="id_comment" name="comentar" type="checkbox">
                                {% endif %}
                            </center>
                        </td>
                        <td>
                            <select class ="form-control categorias" name="categorias" id="id_category">
                                {% for categoria in categorias %}
                                    {% if categoria == post.category %}
                                    <option selected value="{{ categoria }}">{{ categoria }}</option>
                                    {% else %}
                                    <option value="{{ categoria }}">{{ categoria }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </td>
                        <td>
                            <select class ="form-control status" name="status" id="id_status">
                                {% autoescape off %}
                                {% for state in status %}
                                    {% if state.0 == post.status %}
                                    <option selected value="{{ state.0}}">{{ state.1 }}</option>
                                    {% else %}
                                    <option value="{{ state.0 }}">{{ state.1 }}</option>
                                    {% endif %}
                                {% endfor %}
                                {% endautoescape %}
                            </select>
                        </td>
                        <td>
                            <input type="hidden" value="{{ post.id }}">
                            <input class="btn btn-default savedata" type="submit" value="Guardar" disabled="true">
                        </td>
                    </tr>
                    {% endfor %}
                </table>
        </div>
        <script type="text/javascript">
        $(document).ready(function(){
            entries_status();
        });
        </script>
    {% else %}
    <div class="text-center"><p>¡ERROR! no tiene los permisos necesarios, Contacte al Administrador </p></div>
    {% endif %}
</div>
{% endblock %}

blog_system/templates/blog/archive_page.html
        		{% load endless %}
                <!--  POST  -->
                {% paginate 4 posts %}
                {% for post in posts %}
                    <div class="col-md-6">
                        <div class="post-entry">
                            <div class="post-body entry-content" id="post-body">
                                <span>
                                    <div class="entry-image">
                                        <a href="{% url 'post' post.slug %}">
                                            <img class="thumb img-responsive" src="{{ post.image.url }}" style="max-height:200px;">
                                        </a>
                                    </div>
                                </span>
                                <div class="article-container">
                                    <div class="inner-content">
                                        <div class="article-category">
                                            <a href="{% url 'home' %}?category={{ post.category }}" rel="tag"> {{post.category}} </a>
{#                                            <a href="/blog/?category={{ post.categoria }}" rel="tag"> {{post.categoria}} </a>#}
                                        </div>
                                        <div class="clr"></div>
                                        <div class="post-date">
                                            <span class="post-month">{{post.created_at|date:"M"}}</span>
                                            <strong class="post-day">{{post.created_at|date:"d"}}</strong>
                                        </div>
                                        <div class="inner-shadow">
                                        <h2 class="article-title"><a href="{% url 'post' post.slug %}">{{ post.title }}</a></h2>
                                        </div>
                                        <div class="body-post">
                                            {% autoescape off %}
                                                {{ post.abstract|truncatechars:150 }}
                                            {% endautoescape %}
                                        </div>
                                    </div>
                                </div>
                                <div style="clearfix"></div>
                            </div>
                            <div class="post-footer">
                                <div class="post-footer-line post-footer-line-1"></div>
                                <div class="clr"></div>
                                <div class="post-footer-line post-footer-line-2"></div>
                                <div class="post-footer-line post-footer-line-3">
                                    <span class="post-location"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if endlesspagination %}
                    {% show_more %}
                {% else %}
                {% get_pages %}
                <div class="col-lg-12">
                    <nav>
                        <ul class="pagination">
                        {% if pages.previous %}
                            <li>
                            {{ pages.previous}}
                            </li>
                        {% endif %}
                        {% for page in pages %}
                            {% if page.is_current %}
                                <li class="active">{{ page }}</li>
                            {% else %}
                                <li>{{ page }}</li>
                            {% endif %}
                        {% endfor %}
                        {% if pages.next %}
                            <li>
                            {{ pages.next }}
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                {% endif %}
                <!--  END POST  -->

blog_system/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="{% static 'img/facebook.png' %}">

        {% block snippets %}{% endblock %}

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">


        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <!--<script src="{% static 'js/ie-emulation-modes-warning.js'%}"></script>-->
        <script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/addpost.js' %}"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
    <div class="blog-masthead hidden-print">
        <div class="container">
            <nav class="blog-nav">
                <a class="blog-nav-item active" href="{% url 'home' %}">Home</a>
                <a class="blog-nav-item" href="#">New features</a>
                <a class="blog-nav-item" href="#">Press</a>
                <a class="blog-nav-item" href="#">New hires</a>
                <a class="blog-nav-item" href="#">About</a>
            </nav>
        </div>
    </div>
    {% if user.is_superuser %}
        <div class="admin-tools hidden-print">
            <i class="fa fa-cog"></i>
            <ul class="admin-items">
                <li><a href="{% url 'new_post' %}">Nuevo Post</a></li>
                <li><a href="{% url 'edit_entries' %}">Publicaciones</a></li>
                <li><a href="{% url 'categories' %}">Categorias</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
    {% endif %}
    <div class="container">
        <div class="blog-header">
            <h1 class="blog-title">The Framework Blog</h1>
            <p class="lead blog-description">The blog for the Deipi's Framework.</p>
        </div>

        <div class="row">
            {% block contenido %}

            {% endblock %}

            <div class="col-sm-3 blog-sidebar hidden-print">
                            <div class="sidebar-module">
                                <h4>Archives</h4>
                                <ul class="nav nav-pills nav-stacked archive">
                                {% regroup archive by created_at|date:"Y" as year_list %}
                                {% for year in year_list %}
                                    {% regroup year.list by created_at|date:"F" as month_list %}
                                    {% for month in month_list %}
                                    <li>
{#                                        <a href="{% url 'month' year.grouper month.grouper %}">{{ month.grouper }} - {{ year.grouper }}</a>#}
                                        <a href="{% url 'home' %}?year={{ year.grouper }}&month={{ month.grouper }}">{{ month.grouper }} - {{ year.grouper }}</a>
                                    </li>
                                    {% endfor %}
                                {% endfor %}
                                </ul>
                            </div>
                </div><!-- /.blog-sidebar -->
            </div><!-- /.row -->
        </div><!-- /.container -->

                <footer class="blog-footer">
                  <p>Blog by <a href="https://www.deipi.com"> <span id="publusher" itemprop="publisher">Deipi.com</a>.</p>
                  <p>
                    <a href="#" class="hidden-print">Back to top</a>
                  </p>
                </footer>
                <!-- Bootstrap core JavaScript
                ================================================== -->
                <!-- Placed at the end of the document so the pages load faster -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                <script src="{% static 'js/bootstrap.min.js' %}"></script>
                <!--<script src="{% static 'js/docs.min.js' %}"></script>-->
                <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
                <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
              </body>
            </html>

blog_system/templates/blog/categories.html
{% extends 'blog/admin.html' %}
<!-- Container -->
{% block content %}
{% load crispy_forms_tags %}
    {% if True %}
        <div class="text-center">
            <h1>Categotias</h1>
        </div>
        <div class="container">
            <div class="row">
                <table class="table table-striped">
                    <tr>
                        <th class="col-md-1">#</th>
                        <th class="col-md-5">Nombre</th>
                        <th class="col-md-5">Descripción</th>
                        <th class="col-md-1">Borrar</th>
                    </tr>
                {% for element in model %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><p class="name">{{ element }}</p></td>
                        <td><div><p class="description">{{ element }}</p></div></td>
                        <td><input type="submit" value="Eliminar" class="btn btn-danger del_category"></td>
                    </tr>
                {% endfor %}
                </table>
            </div>
            <div>
                <input class="btn btn-default" type="button" id="show-add" value="Agregar Categoria">
            </div>
            <div id="modalform">
                {% crispy form %}
            </div>
        </div>
        <script type="text/javascript">{{ js_functions }}</script>
    {% else %}
    <div class="text-center"><p>¡ERROR! no tiene los permisos necesarios, Contacte al Administrador </p></div>
    {% endif %}

{% endblock %}